version: "3.5"

services:
  redis:
    image: 'bitnami/redis:7.0.13'
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - intranet
    ports:
    - 6379:6379

  postgresql:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: dbuser
      POSTGRES_DB: chuck_norris_joke_app
    networks:
      - intranet
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chuck-norris-api
    env_file:
      - .docker.env
    networks:
      - intranet
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - ./src:/app/src

networks:
  intranet: